name: Java CI with Maven

on:
  workflow_dispatch:  # Enable manual trigger
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-0 libgbm1 libatk-bridge2.0-0 libasound2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libglib2.0-0 libnss3 libnspr4 libdbus-1-3 libatspi2.0-0 libx11-xcb1
        
    - name: Install Playwright with dependencies
      run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install-deps chromium"
        
    - name: Install Playwright Browsers
      run: mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
        
    - name: Run Tests
      run: mvn clean test
      env:
        PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1  # Skip additional browser download since we installed it above
        DISPLAY: :99  # Set up virtual display
      continue-on-error: true
      
    - name: Upload Playwright Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: |
          target/test-results/videos/
          target/test-results/har/
          target/test-results/trace.zip
          target/test-results/report/
        
    - name: Upload TestNG Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: testng-report
        path: |
          target/surefire-reports/*.html
          target/surefire-reports/*.xml